// <auto-generated />
namespace EmployeeRegister.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addCompanypropertytoEmployeeclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCompanypropertytoEmployeeclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201605111214353_add Company property to Employee class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
